# Site settings
title: Yixian HUANG
description: Yixian's Site
# baseurl: "http://huang-yixian.github.io"
# url: http://huang-yixian.github.io

# User settings
username: Yixian HUANG
user_description: Hello! I am a first-year Ph.D. student in <a href="https://education.utexas.edu/departments/special-education/graduate-programs/learning-disabilities-behavioral-disorders">Learning Disabilities and Behavioral Disorders(LD/BD)</a> at the University of Texas at Austin. I am a quantitative researcher, and am interested in randomized controlled trial (RCT) and meta-analysis research.
user_title: Ph.D. Student in Learning Disabilities and Behavioral Disorders(LD/BD)
email: yixian.huang@utexas.edu
personal_website: https://huang-yixian.github.io


# twitter_username: lorem_ipsum
# github_username:  HUANG-Yixian
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']

